version: '3.4'

services:
  catalogdb:
   container_name: catalogdb
   restart: always
   volumes:
   - mongo_data:/data/db
   ports:
   - "27017:27017"

  basketdb:
   container_name: basketdb
   restart: always
   ports:
   - "6379:6379"
   
  discountdb:
   container_name: discountdb
   environment:
     - POSTGRES_USER=admin
     - POSTGRES_PASSWORD=admin1234
     - POSTGRES_DB=DiscountDb
   restart: always
   ports:
     - "5432:5432"
   volumes:
     - postgres_data:/var/lib/postgresql/data/

  orderdb:
   container_name: orderdb
   environment:
     SA_PASSWORD: "@AliReza1395"
     ACCEPT_EULA: "Y"
     MSSQL_PID: "Express"
   restart: always
   ports:
    - "1434:1433"

  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
    - "5673:5672"
    - "15673:15672"
    - "15674:8080"

  pgadmin:
   container_name: pgadmin
   environment:
    - PGADMIN_DEFAULT_EMAIL=re.choopani@gmail.com
    - PGADMIN_DEFAULT_PASSWORD=AliReza1395
   restart: always
   ports:
    - "5050:8080"
   volumes:
    - pgadmin_data:/root/.pgadmin

  portainer:
   container_name: portainer
   restart: always
   ports:
   - "9000:9000"
   volumes:
   - "/var/run/docker.sock:/var/run/docker.sock"
   - "portainer_data:/data"

  catalog.api:
    container_name: catalog.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - "DatabaseSettings:ConnectionString=mongodb://catalogdb:27017"
    depends_on:
      - catalogdb
    ports:
      - "8000:8080"

  basket.api:
    container_name: basket.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - "CacheSettings:ConnectionString=basketdb:6379"
      - "GrpcSettings:DiscountUrl=http://discountgrpc:8080"
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"
    depends_on:
      - basketdb
      - rabbitmq
    ports:
      - "8001:8080"


  discount.api:
    container_name: discount.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - "DatabaseSettings:ConnectionString=Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=admin1234;"
    depends_on:
      - basketdb
    ports:
      - "8002:8080"




  discountgrpc:
    container_name: discountgrpc
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - "DatabaseSettings:ConnectionString=Server=discountdb;Port=5432;Database=DiscountDb;User Id=admin;Password=admin1234;"
    ports:
      - "8003:8080"
    depends_on:
      - discountdb


  ordering.api:
    container_name: ordering.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - "ConnectionStrings:OrderingConnectionString=Server=orderdb;Database=OrderDb;User Id=sa;Password=@AliReza1395;TrustServerCertificate=True;"
      - "EventBusSettings:HostAddress=amqp://guest:guest@rabbitmq:5672"
    ports:
      - "8004:8080"
    depends_on:
      - orderdb
      - rabbitmq


  ocelotapigateways:
    container_name: ocelotapigateways
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
    ports:
      - "8010:8080"
    depends_on:
      - basket.api
      - catalog.api
      - discount.api
      - ordering.api


  shopping.aggregator:
    container_name: shopping.aggregator
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - "ApiSettings:CatalogUrl=http://catalog.api:8080"
      - "ApiSettings:BasketUrl=http://basket.api:8080"
      - "ApiSettings:OrderingUrl=http://ordering.api:8080"
    depends_on:
      - basket.api
      - catalog.api
      - ordering.api
    ports:
      - "8005:8080"

